<?
$PERM["test.php"]["*"]="D";
$PERM["favicon.ico"]["2"]="R";
$PERM["favicon.ico"]["3"]="R";
$PERM["favicon.ico"]["4"]="R";
$PERM["favicon.ico"]["5"]="R";
$PERM["favicon.ico"]["*"]="R";
$PERM["search"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["about"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>