<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Филиалы транспортной компании КИТ");
?>
<?$APPLICATION->IncludeComponent("bitrix:news", "regions", Array(
	"DISPLAY_DATE" => "Y",	
		"DISPLAY_PICTURE" => "Y",	
		"DISPLAY_PREVIEW_TEXT" => "Y",	
		"USE_SHARE" => "Y",	
		"SEF_MODE" => "Y",	
		"AJAX_MODE" => "N",	
		"IBLOCK_TYPE" => "filials",	
		"IBLOCK_ID" => "8",	
		"NEWS_COUNT" => "300",	
		"USE_SEARCH" => "N",	
		"USE_RSS" => "N",	
		"USE_RATING" => "N",	
		"USE_CATEGORIES" => "N",	
		"USE_FILTER" => "N",	
		"SORT_BY1" => "IBLOCK_SECTION_ID",	
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "NAME",	
		"SORT_ORDER2" => "ASC",
		"CHECK_DATES" => "Y",	
		"PREVIEW_TRUNCATE_LEN" => "",	
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",	
		"LIST_FIELD_CODE" => array(	
			0 => "CODE",
			1 => "CREATED_DATE",
			2 => "",
		),
		"LIST_PROPERTY_CODE" => array(	
			0 => "adres",
			1 => "map",
			2 => "regim",
			4 => "phones",
			5 => "email",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",	
		"DISPLAY_NAME" => "Y",	
		"META_KEYWORDS" => "",	
		"META_DESCRIPTION" => "",	
		"BROWSER_TITLE" => "NAME",	
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",	
		"DETAIL_FIELD_CODE" => array(	
			0 => "",
			1 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(	
			0 => "adres",
			1 => "map",
			2 => "regim",
			4 => "phones",
			5 => "email",
		),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",	
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "N",	
		"DETAIL_PAGER_TITLE" => "Страница",	
		"DETAIL_PAGER_TEMPLATE" => "",	
		"DETAIL_PAGER_SHOW_ALL" => "N",	
		"SET_TITLE" => "Y",	
		"SET_STATUS_404" => "N",	
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",	
		"ADD_SECTIONS_CHAIN" => "N",	
		"USE_PERMISSIONS" => "N",	
		"CACHE_TYPE" => "A",	
		"CACHE_TIME" => "0",	
		"CACHE_FILTER" => "N",	
		"CACHE_GROUPS" => "N",	
		"DISPLAY_TOP_PAGER" => "N",	
		"DISPLAY_BOTTOM_PAGER" => "N",	
		"PAGER_TITLE" => "Филиалы",	
		"PAGER_SHOW_ALWAYS" => "Y",	
		"PAGER_TEMPLATE" => ".default",	
		"PAGER_DESC_NUMBERING" => "N",	
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "0",	
		"PAGER_SHOW_ALL" => "Y",	
		"SEF_FOLDER" => "/f/",	
		"AJAX_OPTION_JUMP" => "N",	
		"AJAX_OPTION_STYLE" => "Y",	
		"AJAX_OPTION_HISTORY" => "N",	
		"VARIABLE_ALIASES" => array(
			"news" => "",
			"section" => "",
			"detail" => "",
		),
		"ADD_ELEMENT_CHAIN" => "Y",	
		"SHARE_HIDE" => "N",	
		"SHARE_TEMPLATE" => "",	
		"SHARE_HANDLERS" => "",	
		"SHARE_SHORTEN_URL_LOGIN" => "",	
		"SHARE_SHORTEN_URL_KEY" => "",	
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?>
<?
/*$APPLICATION->IncludeComponent(
	"bitrix:news",
	"regions",
	Array(
		"IBLOCK_TYPE" => "filials",
		"IBLOCK_ID" => "7",
		"NEWS_COUNT" => "2000",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"SORT_BY1" => "NAME",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "",
		"SORT_ORDER2" => "",
		"CHECK_DATES" => "Y",
		"SEF_MODE" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"ADD_ELEMENT_CHAIN" => "N",
		"USE_PERMISSIONS" => "N",
		"DISPLAY_DATE" => "N",
		"DISPLAY_PICTURE" => "N",
		"DISPLAY_PREVIEW_TEXT" => "N",
		"USE_SHARE" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "",
		"LIST_FIELD_CODE" => array("",""),
		"LIST_PROPERTY_CODE" => array("",""),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_ACTIVE_DATE_FORMAT" => "",
		"DETAIL_FIELD_CODE" => array("",""),
		"DETAIL_PROPERTY_CODE" => array("",""),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "N",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "N",
		"PAGER_TEMPLATE" => "",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "Филиалы",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"SEF_FOLDER" => "/f/",
		"AJAX_OPTION_ADDITIONAL" => "",
		"TAGS_CLOUD_ELEMENTS" => "150",
		"PERIOD_NEW_TAGS" => "",
		"DISPLAY_AS_RATING" => "rating",
		"FONT_MAX" => "50",
		"FONT_MIN" => "10",
		"COLOR_NEW" => "3E74E6",
		"COLOR_OLD" => "C0C0C0",
		"TAGS_CLOUD_WIDTH" => "100%",
		"VARIABLE_ALIASES" => Array("news"=>Array(),"section"=>Array(),"detail"=>Array(),),
		"SEF_URL_TEMPLATES" => Array("news"=>"","section"=>"","detail"=>"#ELEMENT_CODE#/"),
		"VARIABLE_ALIASES" => Array(
			"news" => Array(),
			"section" => Array(),
			"detail" => Array(),
		)
	)
);
*/
?>
<?
/*
$APPLICATION->IncludeComponent(
	"bitrix:catalog",
	"regions",
	Array(
		"IBLOCK_TYPE" => "filials",
		"IBLOCK_ID" => "7",
		"TEMPLATE_THEME" => "",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"DETAIL_USE_VOTE_RATING" => "N",
		"DETAIL_USE_COMMENTS" => "N",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SEF_MODE" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "N",
		"USE_ELEMENT_COUNTER" => "Y",
		"USE_FILTER" => "N",
		"FILTER_VIEW_MODE" => "VERTICAL",
		"USE_COMPARE" => "N",
		"PRICE_CODE" => "",
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"BASKET_URL" => "/personal/basket.php",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"USE_PRODUCT_QUANTITY" => "N",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRODUCT_PROPERTIES" => "",
		"SHOW_TOP_ELEMENTS" => "N",
		"TOP_ELEMENT_COUNT" => "9",
		"TOP_LINE_ELEMENT_COUNT" => "3",
		"TOP_ELEMENT_SORT_FIELD" => "",
		"TOP_ELEMENT_SORT_ORDER" => "",
		"TOP_ELEMENT_SORT_FIELD2" => "",
		"TOP_ELEMENT_SORT_ORDER2" => "",
		"TOP_PROPERTY_CODE" => array(0=>"",1=>"",),
		"SECTION_COUNT_ELEMENTS" => "Y",
		"SECTION_TOP_DEPTH" => "3",
		"SECTIONS_VIEW_MODE" => "LIST",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"PAGE_ELEMENT_COUNT" => "30",
		"LINE_ELEMENT_COUNT" => "3",
		"ELEMENT_SORT_FIELD" => "",
		"ELEMENT_SORT_ORDER" => "",
		"ELEMENT_SORT_FIELD2" => "",
		"ELEMENT_SORT_ORDER2" => "",
		"LIST_PROPERTY_CODE" => array(0=>"email",1=>"adres",2=>"map",3=>"regim",4=>"phone",5=>"",),
		"INCLUDE_SUBSECTIONS" => "Y",
		"LIST_META_KEYWORDS" => "-",
		"LIST_META_DESCRIPTION" => "-",
		"LIST_BROWSER_TITLE" => "-",
		"DETAIL_PROPERTY_CODE" => array(0=>"email",1=>"adres",2=>"map",3=>"regim",4=>"phone",5=>"",),
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_DISPLAY_NAME" => "Y",
		"DETAIL_DETAIL_PICTURE_MODE" => "IMG",
		"DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "H",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_IBLOCK_ID" => "",
		"LINK_PROPERTY_SID" => "",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"USE_STORE" => "N",
		"PAGER_TEMPLATE" => "",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"TOP_VIEW_MODE" => "BANNER",
		"ADD_PICT_PROP" => "-",
		"LABEL_PROP" => "-",
		"TOP_ROTATE_TIMER" => "30",
		"SEF_FOLDER" => "/f/",
		"VARIABLE_ALIASES" => Array(),
		"SEF_URL_TEMPLATES" => array("sections"=>"","section"=>"#SECTION_CODE#/","element"=>"#SECTION_ID#/#ELEMENT_ID#/","compare"=>"compare.php?action=#ACTION_CODE#",),
		"VARIABLE_ALIASES" => Array(
		)
	)
);
*/
?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>