<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Задать вопрос директору филиала ТК КИТ в Ярославле");
?>
<p>
	Любой вопрос по работе филиала транспортной компании КИТ в Ярославле Вы можете задать по телефону или отправив эту форму.
</p>
<?$APPLICATION->IncludeComponent(
	"api:main.feedback",
	"bootstrap",
	Array(
		"USE_CAPTCHA" => "N",
		"USE_HIDDEN_PROTECTION" => "Y",
		"REPLACE_FIELD_FROM" => "Y",
		"UNIQUE_FORM_ID" => "90d63044dcb463f4b476fd5ccf2af7ee",
		"OK_TEXT" => "Спасибо, Ваше сообщение принято.",
		"EMAIL_TO" => "dir76@tk-kit.ru",
		"DISPLAY_FIELDS" => array("AUTHOR_NAME","AUTHOR_EMAIL","AUTHOR_PERSONAL_MOBILE","AUTHOR_MESSAGE"),
		"REQUIRED_FIELDS" => array("AUTHOR_NAME","AUTHOR_PERSONAL_MOBILE","AUTHOR_MESSAGE"),
		"CUSTOM_FIELDS" => array(""),
		"ADMIN_EVENT_MESSAGE_ID" => array("8"),
		// "USER_EVENT_MESSAGE_ID" => array(),
		"USER_EVENT_MESSAGE_ID" => array("9"),
		"TITLE_DISPLAY" => "N",
		"FORM_TITLE" => "Какой-то заголовок",
		"FORM_TITLE_LEVEL" => "1",
		"FORM_STYLE_TITLE" => "",
		"FORM_STYLE" => "",
		"FORM_STYLE_DIV" => "",
		"FORM_STYLE_LABEL" => "",
		"FORM_STYLE_TEXTAREA" => "",
		"FORM_STYLE_INPUT" => "",
		"FORM_STYLE_SELECT" => "",
		"FORM_STYLE_SUBMIT" => "",
		"FORM_SUBMIT_VALUE" => "Отправить",
		"INCLUDE_JQUERY" => "N",
		"VALIDTE_REQUIRED_FIELDS" => "Y",
		"INCLUDE_PLACEHOLDER" => "Y",
		"INCLUDE_PRETTY_COMMENTS" => "N",
		"INCLUDE_FORM_STYLER" => "N",
		"HIDE_FORM_AFTER_SEND" => "N",
		"SCROLL_TO_FORM_IF_MESSAGES" => "N",
		"SCROLL_TO_FORM_SPEED" => "1000",
		"BRANCH_ACTIVE" => "N",
		"SHOW_FILES" => "N",
		"USER_AUTHOR_FIO" => "",
		"USER_AUTHOR_NAME" => "",
		"USER_AUTHOR_LAST_NAME" => "",
		"USER_AUTHOR_SECOND_NAME" => "",
		"USER_AUTHOR_EMAIL" => "",
		"USER_AUTHOR_PERSONAL_MOBILE" => "",
		"USER_AUTHOR_WORK_COMPANY" => "",
		"USER_AUTHOR_POSITION" => "",
		"USER_AUTHOR_PROFESSION" => "",
		"USER_AUTHOR_STATE" => "",
		"USER_AUTHOR_CITY" => "",
		"USER_AUTHOR_STREET" => "",
		"USER_AUTHOR_ADRESS" => "",
		"USER_AUTHOR_PERSONAL_PHONE" => "",
		"USER_AUTHOR_WORK_PHONE" => "",
		"USER_AUTHOR_FAX" => "",
		"USER_AUTHOR_MAILBOX" => "",
		"USER_AUTHOR_WORK_MAILBOX" => "",
		"USER_AUTHOR_SKYPE" => "",
		"USER_AUTHOR_ICQ" => "",
		"USER_AUTHOR_WWW" => "",
		"USER_AUTHOR_WORK_WWW" => "",
		"USER_AUTHOR_MESSAGE_THEME" => "",
		"USER_AUTHOR_MESSAGE" => "",
		"USER_AUTHOR_NOTES" => "",
		"AJAX_MODE" => "Y",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"SHOW_CSS_MODAL_AFTER_SEND" => "N",
		"CSS_MODAL_HEADER" => "Информация",
		"CSS_MODAL_FOOTER" => "<a href=\"http://tuning-soft.ru/\" target=\"_blank\">Разработка модуля</a> - Тюнинг Софт",
		"CSS_MODAL_CONTENT" => "<p>Модуль <b>расширенная форма обратной связи битрикс с вложением</b> предназначен для отправки сообщений с сайта, включая код CAPTCHA и скрытую защиту от спама, и отличается от стандартной формы Битрикс:
<br> - <b>отправкой файлов вложениями или ссылками на файл</b>,
<br> - <b>встроенным конструктором форм,</b>
<br> - скрытой защитой от спама,
<br> - работой нескольких форм на одной странице,
<br> - встроенным фирменным валидатором форм,
<br> - 4 встроенными WEB 2.0 шаблонами,
<br> - дополнительными полями со своим именованием,
<br> - и многими другими функциями...
<br>подробнее читайте на странице модуля <a href=\"http://tuning-soft.ru/1c-bitrix/modules/main-feedback/\" target=\"_blank\">Расширенная форма обратной связи</a>
</p>",
		"AJAX_OPTION_ADDITIONAL" => ""
	)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>